import test from "node:test";
import assert from "node:assert/strict";
import { hashPassword, verifyPassword } from "../../src/lib/auth/password";

test("verifyPassword accepts hashes generated by hashPassword", async () => {
  const passwordHash = await hashPassword("Password123!");

  await assert.doesNotReject(() =>
    verifyPassword("Password123!", passwordHash)
  );

  assert.equal(await verifyPassword("Password123!", passwordHash), true);
  assert.equal(await verifyPassword("WrongPassword123!", passwordHash), false);
});

test("verifyPassword normalizes Laravel $2y$ hashes", async () => {
  const passwordHash = await hashPassword("Password123!");
  const laravelStyleHash = `$2y$${passwordHash.slice(4)}`;

  assert.equal(await verifyPassword("Password123!", laravelStyleHash), true);
});
